# Data science tutorials  
### Chapter3 : Numpy

<img style="float: right;" src="img/logo.png" width="150">

<div style="text-align: right"> Initial issue : 2022.01.22 </div>
<div style="text-align: right"> last update : 2022.01.22 </div>

### References
- https://compmath.korea.ac.kr/appmath/NumpyBasics.html
- https://numpy.org/doc/stable/user/quickstart.html

### Objectives  
- Numpy 라이브러리 기본 사용법을 익힌다.

파이썬 언어로 다차원 배열이나 다양한 형태의 데이터를 다루기 위해 수치계산, 데이터분석용 라이브러리를 사용한다.  
Numpy는 벡터 또는 행렬과 같은 다차원 배열의 연산을 쉽게 처리하도록 지원하는 라이브러리이다.

In [1]:
import numpy as np # 라이브러리 사용을 위한 추가

### 1. list vs array  
---
- list : python 기본 자료형  
- ndarray : numpy에서 사용하는 자료형, 벡터, 행렬 연산에 특화됨

#### 1.1 list

In [2]:
# 리스트 생성
data_list = list(range(5))
data_list

[0, 1, 2, 3, 4]

리스트로 타입의 데이터의 각 요소에 2 곱하기 

In [3]:
data_list*2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

- 요소가 두배로 늘어난다.  

리스트 데이터의 각 요소를 정수배 하려면, for loop를 사용해야한다.(불편)

In [4]:
# for loop를 사용
[n*2 for n in data_list]

[0, 2, 4, 6, 8]

#### 1.2 numpy의 `ndarray` 객체 사용하기

In [5]:
data_array = np.array(data_list)

In [6]:
data_array

array([0, 1, 2, 3, 4])

In [7]:
type(data_array)

numpy.ndarray

In [8]:
# 내부 요소의 데이터 타입
data_array.dtype

dtype('int32')

In [9]:
# 데이터 형태
data_array.shape

(5,)

ndarray 타입의 데이터의 각 요소에 2 곱하기
- ndarray를 사용하면 벡터 연산에 용이하다.

In [10]:
data_array*2

array([0, 2, 4, 6, 8])

### 2. 다차원 배열 만들기

In [11]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr = np.array(data)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# 배열의 차원
arr.ndim

2

In [13]:
# 배열의 형태
arr.shape

(2, 4)

### 3. 배열 원소의 자료형

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int64)

In [15]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


### 4. 배열 연산

In [16]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )

In [17]:
A+B

array([[3, 1],
       [3, 5]])

In [18]:
A-B

array([[-1,  1],
       [-3, -3]])

In [19]:
A*B # 행렬 원소 곱셈(elementwise product)

array([[2, 0],
       [0, 4]])

In [20]:
A.dot(B) # 행렬 내적(dot product)

array([[5, 4],
       [3, 4]])

In [21]:
np.dot(A, B) # 행렬 내적(dot product)

array([[5, 4],
       [3, 4]])

### 5. 인덱싱, 슬라이싱

In [22]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[5]

5

In [24]:
arr[5:8]

array([5, 6, 7])

원소 변경하기

In [25]:
arr[5:8] = 10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

다차원 배열의 인덱싱과 슬라이싱

In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d[:2] # row 범위 선택

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr2d[:2, 1:] # row, column 범위 선택

array([[2, 3],
       [5, 6]])

원소 변경하기

In [29]:
arr2d[:2, 1:] = -1
arr2d

array([[ 1, -1, -1],
       [ 4, -1, -1],
       [ 7,  8,  9]])

논리 인덱싱

In [30]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# 3보다 작은 원소 찾기
arr2d < 3

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [32]:
arr2d[arr2d < 3]

array([1, 2])

In [33]:
# 3보다 작은 원소에 -1 대입
arr2d[arr2d < 3] = -1
arr2d

array([[-1, -1,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### 6. 정렬  
---
파이썬의 리스트와 유사하게 정렬 메서드 사용가능

In [34]:
arr = np.array([3, 2, 4, 1, 5])
arr

array([3, 2, 4, 1, 5])

In [35]:
arr.sort()
arr

array([1, 2, 3, 4, 5])